version: '2'
services:
  academy-api:
    build: .
    environment:
      PORT: '4000'
      SHOW_URLS: 'true'
      USERS_PORT: '4001'
      USERS_ENTRY: 'sessions'
      WALLETS_PORT: '4040'
      WALLETS_ENTRY: 'wallets/resources/wallet'
      MATCHES_PORT: '4003'
      MATCHES_ENTRY: 'matches'
      TEAMS_PORT: '4003'
      TEAMS_ENTRY: 'teams'
      WINNERS_PORT: '4004'
      WINNERS_ENTRY: 'winners'
      RESULTS_PORT: '4005'
      RESULTS_ENTRY: 'results'

      # Examples
      # STUDENTS_URL: '192.168.99.101'
      # STUDENTS_PORT: '4000'
      # STUDENTS_ENTRY: 'students/'
      # COURSES_URL: '192.168.99.101'
      # COURSES_PORT: '4001'
      # COURSES_ENTRY: 'courses/'
      # GRADES_URL: '192.168.99.101'
      # GRADES_PORT: '4002'
      # GRADES_ENTRY: 'grades/'
      # USERS_URL: '192.168.99.101'

    ports:
      - '4000:4000'
