version: '2'
services:
  bet-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      USERS_URL: '18.233.69.134'
      USERS_PORT: '4001'
      USERS_ENTRY: 'sessions'
      WALLETS_URL: '35.194.70.72'
      WALLETS_PORT: '4004'
      WALLETS_ENTRY: 'wallets/resources/wallet'
      MATCHES_URL: '52.41.9.11'
      MATCHES_PORT: '4003'
      MATCHES_ENTRY: 'matches'
      TEAMS_URL: '52.41.9.11'
      TEAMS_PORT: '4003'
      TEAMS_ENTRY: 'teams'
      RESULTS_URL: '35.194.70.72'
      RESULTS_PORT: '4005'
      RESULTS_ENTRY: 'results'

      # Examples
      # STUDENTS_URL: '192.168.99.101'
      # STUDENTS_PORT: '4000'
      # STUDENTS_ENTRY: 'students/'

    ports:
      - '5000:5000
